### PR TITLE
add possibilty to specify number of channels to be created when mounting Oracle as View

### PR DESCRIPTION
**Pull request by maduma**

### CODE REVIEW

**Comment by bseltz-cohesity** [comment]
Number of channels does not apply to oracle recovery as a view. Rejecting.

**Comment by maduma** [comment]
Please have a look on this. I mimic the when gui options, where you can configure channel.
image

You can see here that indeed there are 8 NFS mounts on the server 
```
> python .\mountOracleAsView.py -v cohesity -u admin -pwd 'xxxxxxxxxxxxxxxxxxx' -ss syts00dbts.int.hs.lu -sd syts00 -ts test1dbts.int.hs.lu  -l -w
Connected!
Mounting DB syts00 to test1dbts.int.hs.lu as view syts00...
Restore Completed Successfully
> ssh test1dbts.int.hs.lu mount | Select-String DefaultStorageDomain

/tmp/syts00/oracle_260604_74_path0 on 172.16.157.16:/DefaultStorageDomain/cohesity_int_260604_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3daa on Fri Jun 14 10:35:50 2024
/tmp/syts00/oracle_260604_74_path1 on 172.16.157.15:/DefaultStorageDomain/cohesity_int_260604_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3dab on Fri Jun 14 10:35:50 2024
/tmp/syts00/oracle_260604_74_path2 on 172.16.157.18:/DefaultStorageDomain/cohesity_int_260604_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3dac on Fri Jun 14 10:35:51 2024
/tmp/syts00/oracle_260604_74_path3 on 172.16.157.17:/DefaultStorageDomain/cohesity_int_260604_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3dad on Fri Jun 14 10:35:51 2024


> python .\destroyClone.py -v cohesity -u admin -pwd 'xxxxxxxxxxxxxxxxxxx' -t oracle_view -o syts00 -w
Connected!
tearing down View: syts00
> ssh test1dbts.int.hs.lu mount | Select-String DefaultStorageDomain
> python .\mountOracleAsView.py -v cohesity1.int.hs.lu -u admin -pwd 'xxxxxxxxxxxxxxxxxxx' -ss syts00dbts.int.hs.lu -sd syts00 -ts test1dbts.int.hs.lu -cc 8 -l -w
Connected!
Mounting DB syts00 to test1dbts.int.hs.lu as view syts00...
Restore Completed Successfully
> ssh test1dbts.int.hs.lu mount | Select-String DefaultStorageDomain

/tmp/syts00/oracle_260609_74_path0 on 172.16.157.16:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3dae on Fri Jun 14 10:38:10 2024
/tmp/syts00/oracle_260609_74_path1 on 172.16.157.15:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3daf on Fri Jun 14 10:38:11 2024
/tmp/syts00/oracle_260609_74_path2 on 172.16.157.18:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db0 on Fri Jun 14 10:38:11 2024
/tmp/syts00/oracle_260609_74_path3 on 172.16.157.17:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db1 on Fri Jun 14 10:38:12 2024
/tmp/syts00/oracle_260609_74_path4 on 172.16.157.16:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db2 on Fri Jun 14 10:38:12 2024
/tmp/syts00/oracle_260609_74_path5 on 172.16.157.15:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db3 on Fri Jun 14 10:38:13 2024
/tmp/syts00/oracle_260609_74_path6 on 172.16.157.18:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db4 on Fri Jun 14 10:38:13 2024
/tmp/syts00/oracle_260609_74_path7 on 172.16.157.17:/DefaultStorageDomain/cohesity_int_260609_2b181/fs
remote/read/write/setuid/nodevices/rstchown/bg/hard/nointr/rsize=32768/wsize=32768/proto=tcp/noac/forcedirectio/vers=3/xattr/zone=test1dbts/sharezone=4/dev=ffbc3db5 on Fri Jun 14 10:38:13 2024


> python .\destroyClone.py -v cohesity -u admin -pwd 'xxxxxxxxxxxxxxxxxxx' -t oracle_view -o syts00 -w
Connected!
tearing down View: syts00
```

**Comment by bseltz-cohesity** [comment]
OK I see. I had to modify the code to get it to work in my testing. Can you please verify that my changes work in your environment. The updated script is here: https://github.com/cohesity/community-automation-samples/tree/main/oracle/python/mountOracleAsView

**Comment by maduma** [comment]
Thanks is working fine.

My first PR actually contains a bug 😥. Your code is actually the same as mine😃

https://github.com/maduma/community-automation-samples/blob/main/oracle/python/mountOracleAsView/mountOracleAsView.py

**Comment by bseltz-cohesity** [comment]
Thanks for the contribution.

**Pull request closed without merging**
